# Generated by Django 3.2.9 on 2022-03-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe_backend', '0002_auto_20220306_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='lobby_id',
            new_name='lobby',
        ),
        migrations.RenameField(
            model_name='boardcolor',
            old_name='board_id',
            new_name='board',
        ),
    ]
